package vscode_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/johnkil/polyrepo-workspace-kit/internal/vscode"
	"github.com/johnkil/polyrepo-workspace-kit/internal/workspace"
)

func TestBuildPlanRendersVSCodeWorkspace(t *testing.T) {
	root, _, _ := seedVSCodeWorkspace(t)
	if err := os.MkdirAll(filepath.Join(root, "coordination", "scenarios", "schema-rollout"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "coordination", "scenarios", "schema-rollout", "manifest.lock.yaml"), []byte("version: 1\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	plan, err := vscode.BuildPlan(root, vscode.PlanOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Targets) != 1 {
		t.Fatalf("expected one target, got %#v", plan.Targets)
	}
	target := plan.Targets[0]
	if target.Status != vscode.StatusNew {
		t.Fatalf("expected new target, got %#v", target)
	}
	for _, want := range []string{
		`"name": "app-web"`,
		`"name": "shared-schema"`,
		`"label": "wkit: validate"`,
		`"label": "scenario: schema-rollout: run"`,
		`"label": "app-web: test"`,
		`"cwd": "${workspaceFolder:app-web}"`,
		`"scm.alwaysShowRepositories": true`,
		"generated by wkit",
	} {
		if !strings.Contains(target.RenderedText, want) {
			t.Fatalf("expected rendered workspace to contain %q:\n%s", want, target.RenderedText)
		}
	}
	var decoded map[string]any
	if err := json.Unmarshal([]byte(stripJSONCComments(target.RenderedText)), &decoded); err != nil {
		t.Fatalf("rendered workspace is not valid JSON after comments are stripped: %v\n%s", err, target.RenderedText)
	}
}

func TestBuildPlanRejectsMissingBinding(t *testing.T) {
	root := filepath.Join(t.TempDir(), "workspace")
	if err := workspace.Init(root); err != nil {
		t.Fatal(err)
	}
	if _, err := workspace.RegisterRepo(root, "app-web", "app"); err != nil {
		t.Fatal(err)
	}

	_, err := vscode.BuildPlan(root, vscode.PlanOptions{})
	if err == nil || !strings.Contains(err.Error(), "missing local binding") {
		t.Fatalf("expected missing binding error, got %v", err)
	}
}

func TestApplyWritesAndProtectsVSCodeWorkspace(t *testing.T) {
	root, _, _ := seedVSCodeWorkspace(t)
	targetPath, err := vscode.TargetPath(root)
	if err != nil {
		t.Fatal(err)
	}

	result, err := vscode.Apply(root, vscode.PlanOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Written) != 1 {
		t.Fatalf("expected one write, got %#v", result.Written)
	}
	assertFileExists(t, targetPath)

	result, err = vscode.Apply(root, vscode.PlanOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Skipped) != 1 {
		t.Fatalf("expected unchanged target to be skipped, got %#v", result)
	}

	if err := os.WriteFile(targetPath, []byte("custom\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	blocked, err := vscode.BuildPlan(root, vscode.PlanOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if blocked.Targets[0].Status != vscode.StatusBlocked {
		t.Fatalf("expected changed target to be blocked, got %#v", blocked.Targets[0])
	}

	result, err = vscode.Apply(root, vscode.PlanOptions{
		Backup: true,
		Now:    time.Date(2026, 4, 20, 12, 0, 0, 0, time.UTC),
	})
	if err != nil {
		t.Fatal(err)
	}
	backupPath := targetPath + ".bak.20260420T120000Z"
	backup, err := os.ReadFile(backupPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(backup) != "custom\n" {
		t.Fatalf("unexpected backup content: %q", string(backup))
	}
	if len(result.Written) != 1 || result.Written[0].BackupPath != backupPath {
		t.Fatalf("unexpected backup apply result: %#v", result)
	}
}

func TestBuildPlanBlocksSymlinkParentEscape(t *testing.T) {
	root, _, _ := seedVSCodeWorkspace(t)
	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(root, "local", "vscode")); err != nil {
		t.Fatal(err)
	}

	plan, err := vscode.BuildPlan(root, vscode.PlanOptions{})
	if err != nil {
		t.Fatal(err)
	}
	target := plan.Targets[0]
	if target.Status != vscode.StatusBlocked {
		t.Fatalf("expected symlink parent to be blocked, got %#v", target)
	}
	if !strings.Contains(strings.Join(target.Notes, "\n"), "unsafe target path") {
		t.Fatalf("expected unsafe target note, got %#v", target.Notes)
	}
	if _, err := vscode.Apply(root, vscode.PlanOptions{}); err == nil {
		t.Fatal("expected apply to fail on symlink parent escape")
	}
	assertFileMissing(t, filepath.Join(outside, "workspace.code-workspace"))
}

func seedVSCodeWorkspace(t *testing.T) (string, string, string) {
	t.Helper()
	root := filepath.Join(t.TempDir(), "workspace")
	if err := workspace.Init(root); err != nil {
		t.Fatal(err)
	}
	if _, err := workspace.RegisterRepo(root, "app-web", "app"); err != nil {
		t.Fatal(err)
	}
	if _, err := workspace.RegisterRepo(root, "shared-schema", "contract"); err != nil {
		t.Fatal(err)
	}
	app := filepath.Join(t.TempDir(), "app-web")
	schema := filepath.Join(t.TempDir(), "shared-schema")
	if err := os.MkdirAll(app, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(schema, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := workspace.SetBinding(root, "app-web", app); err != nil {
		t.Fatal(err)
	}
	if _, err := workspace.SetBinding(root, "shared-schema", schema); err != nil {
		t.Fatal(err)
	}
	return root, app, schema
}

func stripJSONCComments(text string) string {
	var lines []string
	for _, line := range strings.Split(text, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "//") {
			continue
		}
		lines = append(lines, line)
	}
	return strings.Join(lines, "\n")
}

func assertFileExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Fatal(err)
	}
}

func assertFileMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Fatalf("expected %s to be missing", path)
	} else if !os.IsNotExist(err) {
		t.Fatal(err)
	}
}
